### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by Clue355** [Clue355/card-game_front-end#2]
Create the homepage

### TODO
- [ ] add the background
- [ ] add the title
- [ ] add the button
- [ ] make sure the button goes to the gameboard
